@startuml

interface InputView {
+ receiveInput(): GameInput
}

class RacingGameInputView {
+ receiveInput(): GameInput
}

class GameInput {
+ numberOfCars: Int
+ numberOfRounds: Int
}

interface ResultView {
+ printResult(gameResult: GameResult)
}

class GameResult {
+ roundResults: List<RoundResult>
}

class RacingGameResultView implements ResultView {
+ printResult(gameResult: GameResult)
}

interface FuelProvider {
+ getFuel(): Int
}

class RandomFuelProvider {
+ getFuel(): Int
}

class Car {
+ carId: Int
+ accelerate(fuel: Int)
}

class RacingGame {
+ run(input: GameInput): GameResult
}

RacingGame *-left-> "*" Car
RacingGame -> FuelProvider
RandomFuelProvider .left.|> FuelProvider

RacingGame -up-> GameInput
InputView -down-> GameInput
RacingGameInputView ..|> InputView

RacingGame -down-> GameResult
ResultView -up-> GameResult

@enduml